//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTV.jzIntv.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INTV.jzIntv.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string DisplayGroupCommand_Name {
            get {
                return ResourceManager.GetString("DisplayGroupCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ECS.
        /// </summary>
        internal static string EnableEcsCommand_Name {
            get {
                return ResourceManager.GetString("EnableEcsCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Intellivoice.
        /// </summary>
        internal static string EnableIntellivoiceCommand_Name {
            get {
                return ResourceManager.GetString("EnableIntellivoiceCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        internal static string HardwareGroupCommand_Name {
            get {
                return ResourceManager.GetString("HardwareGroupCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv encountered an error when running
        ///  &apos;{0}&apos;
        ///
        ///and exited with error: {1}
        ///.
        /// </summary>
        internal static string jzIntvExitedWithError_MessageFormat {
            get {
                return ResourceManager.GetString("jzIntvExitedWithError_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv.
        /// </summary>
        internal static string JzIntvTabCommand_Name {
            get {
                return ResourceManager.GetString("JzIntvTabCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Keys.
        /// </summary>
        internal static string KeyboardMap_CommandKeys {
            get {
                return ResourceManager.GetString("KeyboardMap_CommandKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string KeyboardMap_Default {
            get {
                return ResourceManager.GetString("KeyboardMap_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS Keyboard.
        /// </summary>
        internal static string KeyboardMap_EcsKeyboard {
            get {
                return ResourceManager.GetString("KeyboardMap_EcsKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Controller Only.
        /// </summary>
        internal static string KeyboardMap_LeftControllerOnly {
            get {
                return ResourceManager.GetString("KeyboardMap_LeftControllerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string SetDisplayModeFullscreenCommand_Name {
            get {
                return ResourceManager.GetString("SetDisplayModeFullscreenCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string SetDisplayResolutionCommand_Name {
            get {
                return ResourceManager.GetString("SetDisplayResolutionCommand_Name", resourceCulture);
            }
        }
    }
}
