
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class SplashScreen
	{
		private global::Gtk.Image _splashImage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.SplashScreen
			this.Name = "INTV.Shared.View.SplashScreen";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.AcceptFocus = false;
			this.Decorated = false;
			this.SkipTaskbarHint = true;
			// Container child INTV.Shared.View.SplashScreen.Gtk.Container+ContainerChild
			this._splashImage = new global::Gtk.Image ();
			this._splashImage.Name = "_splashImage";
			this.Add (this._splashImage);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Hide ();
		}
	}
}
