
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class RomListView
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView _romListView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.RomListView
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 300;
			this.Name = "INTV.Shared.View.RomListView";
			// Container child INTV.Shared.View.RomListView.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this._romListView = new global::Gtk.TreeView ();
			this._romListView.CanFocus = true;
			this._romListView.Name = "_romListView";
			this.GtkScrolledWindow.Add (this._romListView);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this._romListView.FocusInEvent += new global::Gtk.FocusInEventHandler (this.HandleRomListFocusIn);
			this._romListView.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.HandleRomListFocusOut);
			this._romListView.DragDataDelete += new global::Gtk.DragDataDeleteHandler (this.HandleDragDataDelete);
			this._romListView.DragBegin += new global::Gtk.DragBeginHandler (this.HandleDragBegin);
			this._romListView.DragDataReceived += new global::Gtk.DragDataReceivedHandler (this.HandleDragDataReceived);
			this._romListView.DragDataGet += new global::Gtk.DragDataGetHandler (this.HandleDragDataGet);
			this._romListView.DragDrop += new global::Gtk.DragDropHandler (this.HandleDragDrop);
			this._romListView.DragEnd += new global::Gtk.DragEndHandler (this.HandleDragEnd);
			this._romListView.DragLeave += new global::Gtk.DragLeaveHandler (this.HandleDragLeave);
			this._romListView.DragMotion += new global::Gtk.DragMotionHandler (this.HandleDragMotion);
		}
	}
}
