
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class DragDropImage
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image _dragIcon;
		
		private global::Gtk.Label _dragText;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.DragDropImage
			this.Name = "INTV.Shared.View.DragDropImage";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowShrink = true;
			this.AcceptFocus = false;
			this.FocusOnMap = false;
			// Container child INTV.Shared.View.DragDropImage.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(4));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(2));
			this.GtkAlignment.TopPadding = ((uint)(2));
			this.GtkAlignment.RightPadding = ((uint)(2));
			this.GtkAlignment.BottomPadding = ((uint)(2));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this._dragIcon = new global::Gtk.Image ();
			this._dragIcon.Name = "_dragIcon";
			this._dragIcon.Xalign = 0F;
			this.hbox1.Add (this._dragIcon);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._dragIcon]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this._dragText = new global::Gtk.Label ();
			this._dragText.Name = "_dragText";
			this._dragText.Xalign = 0F;
			this._dragText.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this._dragText);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._dragText]));
			w2.Position = 1;
			this.GtkAlignment.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
