
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class ProgressIndicator
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Alignment alignment6;
		
		private global::Gtk.Label _progressTitle;
		
		private global::Gtk.Alignment alignment4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Alignment alignment5;
		
		private global::Gtk.ProgressBar _progressBar;
		
		private global::Gtk.Button _cancel;
		
		private global::Gtk.Alignment alignment7;
		
		private global::Gtk.Label _updateText;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.ProgressIndicator
			this.Name = "INTV.Shared.View.ProgressIndicator";
			this.Title = global::Mono.Unix.Catalog.GetString ("ProgressIndicator.Gtk");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.Decorated = false;
			// Container child INTV.Shared.View.ProgressIndicator.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.alignment6.LeftPadding = ((uint)(8));
			this.alignment6.TopPadding = ((uint)(8));
			this.alignment6.RightPadding = ((uint)(8));
			// Container child alignment6.Gtk.Container+ContainerChild
			this._progressTitle = new global::Gtk.Label ();
			this._progressTitle.Name = "_progressTitle";
			this._progressTitle.Xalign = 0F;
			this._progressTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.alignment6.Add (this._progressTitle);
			this.vbox2.Add (this.alignment6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment6]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(8));
			this.alignment4.TopPadding = ((uint)(4));
			this.alignment4.RightPadding = ((uint)(8));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.TopPadding = ((uint)(6));
			this.alignment5.BottomPadding = ((uint)(6));
			// Container child alignment5.Gtk.Container+ContainerChild
			this._progressBar = new global::Gtk.ProgressBar ();
			this._progressBar.Name = "_progressBar";
			this.alignment5.Add (this._progressBar);
			this.hbox1.Add (this.alignment5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment5]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this._cancel = new global::Gtk.Button ();
			this._cancel.CanFocus = true;
			this._cancel.Name = "_cancel";
			this._cancel.UseUnderline = true;
			this._cancel.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox1.Add (this._cancel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._cancel]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.alignment4.Add (this.hbox1);
			this.vbox2.Add (this.alignment4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.alignment7.LeftPadding = ((uint)(8));
			this.alignment7.RightPadding = ((uint)(8));
			this.alignment7.BottomPadding = ((uint)(8));
			// Container child alignment7.Gtk.Container+ContainerChild
			this._updateText = new global::Gtk.Label ();
			this._updateText.Name = "_updateText";
			this._updateText.Xalign = 0F;
			this._updateText.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this._updateText.Ellipsize = ((global::Pango.EllipsizeMode)(2));
			this.alignment7.Add (this._updateText);
			this.vbox2.Add (this.alignment7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment7]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Hide ();
			this._cancel.Clicked += new global::System.EventHandler (this.HandleCancelClicked);
		}
	}
}
