
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class SerialPortSelector
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label _prompt;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView _ports;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.ComboBox _baudRates;
		
		private global::Gtk.Label _baudRateLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.SerialPortSelector
			global::Stetic.BinContainer.Attach (this);
			this.Name = "INTV.Shared.View.SerialPortSelector";
			// Container child INTV.Shared.View.SerialPortSelector.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this._prompt = new global::Gtk.Label ();
			this._prompt.Name = "_prompt";
			this._prompt.Xalign = 0F;
			this._prompt.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this._prompt.Wrap = true;
			this.vbox1.Add (this._prompt);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._prompt]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this._ports = new global::Gtk.TreeView ();
			this._ports.CanFocus = true;
			this._ports.Name = "_ports";
			this.GtkScrolledWindow.Add (this._ports);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this._baudRates = new global::Gtk.ComboBox ();
			this._baudRates.Name = "_baudRates";
			this.hbox1.Add (this._baudRates);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._baudRates]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this._baudRateLabel = new global::Gtk.Label ();
			this._baudRateLabel.Name = "_baudRateLabel";
			this._baudRateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.hbox1.Add (this._baudRateLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._baudRateLabel]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
