
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class GeneralFeaturesConfigurationPage
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.GeneralFeaturesConfigurationPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "INTV.Shared.View.GeneralFeaturesConfigurationPage";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
