
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class RomListSettingsPage
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.CheckButton _validateAtLaunch;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.CheckButton _searchForRomsAtLaunch;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView _directories;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.CheckButton _displayRomFileNameForTitle;
		
		private global::Gtk.CheckButton _showRomDetails;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.RomListSettingsPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "INTV.Shared.View.RomListSettingsPage";
			// Container child INTV.Shared.View.RomListSettingsPage.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 4;
			// Container child vbox2.Gtk.Box+BoxChild
			this._validateAtLaunch = new global::Gtk.CheckButton ();
			this._validateAtLaunch.CanFocus = true;
			this._validateAtLaunch.Name = "_validateAtLaunch";
			this._validateAtLaunch.Label = global::Mono.Unix.Catalog.GetString ("Validate ROMs at application startup");
			this._validateAtLaunch.DrawIndicator = true;
			this._validateAtLaunch.UseUnderline = true;
			this.vbox2.Add (this._validateAtLaunch);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this._validateAtLaunch]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(2));
			// Container child vbox3.Gtk.Box+BoxChild
			this._searchForRomsAtLaunch = new global::Gtk.CheckButton ();
			this._searchForRomsAtLaunch.CanFocus = true;
			this._searchForRomsAtLaunch.Name = "_searchForRomsAtLaunch";
			this._searchForRomsAtLaunch.Label = global::Mono.Unix.Catalog.GetString ("Scan for ROMs at application startup");
			this._searchForRomsAtLaunch.DrawIndicator = true;
			this._searchForRomsAtLaunch.UseUnderline = true;
			this.vbox3.Add (this._searchForRomsAtLaunch);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this._searchForRomsAtLaunch]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this._directories = new global::Gtk.TreeView ();
			this._directories.CanFocus = true;
			this._directories.Name = "_directories";
			this._directories.HeadersVisible = false;
			this.GtkScrolledWindow.Add (this._directories);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w4.Position = 1;
			this.GtkAlignment.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ROM Directories</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w7.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this._displayRomFileNameForTitle = new global::Gtk.CheckButton ();
			this._displayRomFileNameForTitle.CanFocus = true;
			this._displayRomFileNameForTitle.Name = "_displayRomFileNameForTitle";
			this._displayRomFileNameForTitle.Label = global::Mono.Unix.Catalog.GetString ("Display ROM file name for title");
			this._displayRomFileNameForTitle.DrawIndicator = true;
			this._displayRomFileNameForTitle.UseUnderline = true;
			this.vbox2.Add (this._displayRomFileNameForTitle);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this._displayRomFileNameForTitle]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this._showRomDetails = new global::Gtk.CheckButton ();
			this._showRomDetails.CanFocus = true;
			this._showRomDetails.Name = "_showRomDetails";
			this._showRomDetails.Label = global::Mono.Unix.Catalog.GetString ("Show detailed ROM information");
			this._showRomDetails.DrawIndicator = true;
			this._showRomDetails.UseUnderline = true;
			this.vbox2.Add (this._showRomDetails);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this._showRomDetails]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this._validateAtLaunch.Toggled += new global::System.EventHandler (this.HandleValidateAtLaunchToggled);
			this._searchForRomsAtLaunch.Toggled += new global::System.EventHandler (this.HandleSearchForRomsAtLaunchToggled);
			this._displayRomFileNameForTitle.Toggled += new global::System.EventHandler (this.HandleDisplayRomFileNameForTitleToggled);
			this._showRomDetails.Toggled += new global::System.EventHandler (this.HandleShowRomDetailsToggled);
		}
	}
}
