
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.Shared.View
{
	public partial class ProgressIndicatorOverlay
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.Shared.View.ProgressIndicatorOverlay
			this.Sensitive = false;
			this.Name = "INTV.Shared.View.ProgressIndicatorOverlay";
			this.Title = global::Mono.Unix.Catalog.GetString ("overlay");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(5));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.AcceptFocus = false;
			this.Decorated = false;
			this.FocusOnMap = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Hide ();
		}
	}
}
