//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locutus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Locutus.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string AllFiles_Filter {
            get {
                return ResourceManager.GetString("AllFiles_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured and the application must close. Please include the information below, and a description of what caused the problem..
        /// </summary>
        internal static string CrashDialog_Apology {
            get {
                return ResourceManager.GetString("CrashDialog_Apology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string CrashDialog_CopyToClipboard {
            get {
                return ResourceManager.GetString("CrashDialog_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CrashDialog_Exit {
            get {
                return ResourceManager.GetString("CrashDialog_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string CrashDialog_Title {
            get {
                return ResourceManager.GetString("CrashDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System ROM Files.
        /// </summary>
        internal static string EmulatorFile_Bin_Filter {
            get {
                return ResourceManager.GetString("EmulatorFile_Bin_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate the ECS ROM.
        /// </summary>
        internal static string EmulatorFile_Ecs_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_Ecs_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files.
        /// </summary>
        internal static string EmulatorFile_Exe_Filter {
            get {
                return ResourceManager.GetString("EmulatorFile_Exe_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate the EXEC ROM.
        /// </summary>
        internal static string EmulatorFile_Exec_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_Exec_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate the Graphics ROM.
        /// </summary>
        internal static string EmulatorFile_Grom_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_Grom_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate the jzIntv executable.
        /// </summary>
        internal static string EmulatorFile_JzIntv_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_JzIntv_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Configuration Files.
        /// </summary>
        internal static string EmulatorFile_KeyboardConfig_Filter {
            get {
                return ResourceManager.GetString("EmulatorFile_KeyboardConfig_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate the Keyboard Configuration File.
        /// </summary>
        internal static string EmulatorFile_KeyboardConfig_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_KeyboardConfig_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program uses the ECS, but it is not enabled..
        /// </summary>
        internal static string EmulatorSettings_EcsNotEnabled {
            get {
                return ResourceManager.GetString("EmulatorSettings_EcsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program uses Intellivoice, but it is not enabled..
        /// </summary>
        internal static string EmulatorSettings_IntellivoiceNotEnabled {
            get {
                return ResourceManager.GetString("EmulatorSettings_IntellivoiceNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to ECS.bin is invalid..
        /// </summary>
        internal static string EmulatorSettings_InvalidEcsPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidEcsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to EXEC.bin is invalid..
        /// </summary>
        internal static string EmulatorSettings_InvalidExecPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidExecPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to GROM.bin is invalid..
        /// </summary>
        internal static string EmulatorSettings_InvalidGromPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidGromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to jzIntv is invalid..
        /// </summary>
        internal static string EmulatorSettings_InvalidJzIntvPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidJzIntvPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Keyboard Configuration file is invalid..
        /// </summary>
        internal static string EmulatorSettings_InvalidKeyboardHackPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidKeyboardHackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to set an unkown emulator ROM file..
        /// </summary>
        internal static string EmulatorSettings_InvalidRomFile {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidRomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program is selected..
        /// </summary>
        internal static string EmulatorSettings_NoProgramSelected {
            get {
                return ResourceManager.GetString("EmulatorSettings_NoProgramSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTO Flash!.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Items.
        /// </summary>
        internal static string StatusBar_NumItemsFormat {
            get {
                return ResourceManager.GetString("StatusBar_NumItemsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv is unable to launch because of the following conditions:.
        /// </summary>
        internal static string StatusMessage_ErrorDescription {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch jzIntv. This may be due to missing required files (such as EXEC.bin or GROM.bin), or the jzIntv executable cannot be found. Please ensure your configuration is correct..
        /// </summary>
        internal static string StatusMessage_ErrorFooterDescription {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorFooterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Are Incorrect.
        /// </summary>
        internal static string StatusMessage_ErrorFooterTitle {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorFooterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Start jzIntv.
        /// </summary>
        internal static string StatusMessage_ErrorTitle {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv is configured and ready to play {0}!.
        /// </summary>
        internal static string StatusMessage_NoErrorsOrWarningsDescription {
            get {
                return ResourceManager.GetString("StatusMessage_NoErrorsOrWarningsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start jzIntv.
        /// </summary>
        internal static string StatusMessage_NoErrorsOrWarningsTitle {
            get {
                return ResourceManager.GetString("StatusMessage_NoErrorsOrWarningsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv is able to launch, but {0} may not play correctly due to the following conditions:.
        /// </summary>
        internal static string StatusMessage_WarningDescription {
            get {
                return ResourceManager.GetString("StatusMessage_WarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although jzIntv may be launched, the settings for {0} may not be correct to fully enjoy the program. Make sure the proper hardware has been enabled, and that any support ROMs are properly configured..
        /// </summary>
        internal static string StatusMessage_WarningFooterDescription {
            get {
                return ResourceManager.GetString("StatusMessage_WarningFooterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings May Be Incorrect.
        /// </summary>
        internal static string StatusMessage_WarningFooterTitle {
            get {
                return ResourceManager.GetString("StatusMessage_WarningFooterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start jzIntv (Program May Not Run Correctly).
        /// </summary>
        internal static string StatusMessage_WarningTitle {
            get {
                return ResourceManager.GetString("StatusMessage_WarningTitle", resourceCulture);
            }
        }
    }
}
