//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locutus.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Locutus.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmulatorFile_Bin_Filter {
            get {
                return ResourceManager.GetString("EmulatorFile_Bin_Filter", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_Ecs_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_Ecs_Prompt", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_Exec_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_Exec_Prompt", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_Exe_Filter {
            get {
                return ResourceManager.GetString("EmulatorFile_Exe_Filter", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_Grom_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_Grom_Prompt", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_KeyboardConfig_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_KeyboardConfig_Prompt", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_JzIntv_Prompt {
            get {
                return ResourceManager.GetString("EmulatorFile_JzIntv_Prompt", resourceCulture);
            }
        }
        
        internal static string EmulatorFile_KeyboardConfig_Filter {
            get {
                return ResourceManager.GetString("EmulatorFile_KeyboardConfig_Filter", resourceCulture);
            }
        }
        
        internal static string AllFiles_Filter {
            get {
                return ResourceManager.GetString("AllFiles_Filter", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_EcsNotEnabled {
            get {
                return ResourceManager.GetString("EmulatorSettings_EcsNotEnabled", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_IntellivoiceNotEnabled {
            get {
                return ResourceManager.GetString("EmulatorSettings_IntellivoiceNotEnabled", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_InvalidEcsPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidEcsPath", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_InvalidExecPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidExecPath", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_InvalidGromPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidGromPath", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_InvalidJzIntvPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidJzIntvPath", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_InvalidKeyboardHackPath {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidKeyboardHackPath", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_InvalidRomFile {
            get {
                return ResourceManager.GetString("EmulatorSettings_InvalidRomFile", resourceCulture);
            }
        }
        
        internal static string EmulatorSettings_NoProgramSelected {
            get {
                return ResourceManager.GetString("EmulatorSettings_NoProgramSelected", resourceCulture);
            }
        }
        
        internal static string StatusMessage_ErrorDescription {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorDescription", resourceCulture);
            }
        }
        
        internal static string StatusMessage_ErrorFooterDescription {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorFooterDescription", resourceCulture);
            }
        }
        
        internal static string StatusMessage_ErrorFooterTitle {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorFooterTitle", resourceCulture);
            }
        }
        
        internal static string StatusMessage_ErrorTitle {
            get {
                return ResourceManager.GetString("StatusMessage_ErrorTitle", resourceCulture);
            }
        }
        
        internal static string StatusMessage_NoErrorsOrWarningsDescription {
            get {
                return ResourceManager.GetString("StatusMessage_NoErrorsOrWarningsDescription", resourceCulture);
            }
        }
        
        internal static string StatusMessage_NoErrorsOrWarningsTitle {
            get {
                return ResourceManager.GetString("StatusMessage_NoErrorsOrWarningsTitle", resourceCulture);
            }
        }
        
        internal static string StatusMessage_WarningDescription {
            get {
                return ResourceManager.GetString("StatusMessage_WarningDescription", resourceCulture);
            }
        }
        
        internal static string StatusMessage_WarningFooterDescription {
            get {
                return ResourceManager.GetString("StatusMessage_WarningFooterDescription", resourceCulture);
            }
        }
        
        internal static string StatusMessage_WarningFooterTitle {
            get {
                return ResourceManager.GetString("StatusMessage_WarningFooterTitle", resourceCulture);
            }
        }
        
        internal static string StatusMessage_WarningTitle {
            get {
                return ResourceManager.GetString("StatusMessage_WarningTitle", resourceCulture);
            }
        }
        
        internal static string StatusBar_NumItemsFormat {
            get {
                return ResourceManager.GetString("StatusBar_NumItemsFormat", resourceCulture);
            }
        }
        
        internal static string CrashDialog_Apology {
            get {
                return ResourceManager.GetString("CrashDialog_Apology", resourceCulture);
            }
        }
        
        internal static string CrashDialog_CopyToClipboard {
            get {
                return ResourceManager.GetString("CrashDialog_CopyToClipboard", resourceCulture);
            }
        }
        
        internal static string CrashDialog_Exit {
            get {
                return ResourceManager.GetString("CrashDialog_Exit", resourceCulture);
            }
        }
        
        internal static string CrashDialog_Title {
            get {
                return ResourceManager.GetString("CrashDialog_Title", resourceCulture);
            }
        }
        
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        internal static string ApplicationDisplayName {
            get {
                return ResourceManager.GetString("ApplicationDisplayName", resourceCulture);
            }
        }
        
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        internal static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        internal static string PrimarySplitterPosition {
            get {
                return ResourceManager.GetString("PrimarySplitterPosition", resourceCulture);
            }
        }
    }
}
