// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace INTV.JzIntvUI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("INTV.JzIntvUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SettingsPage_General_EnableIntellivoice_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableIntellivoice_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick3Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick3Config_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_ResetExecPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetExecPath_Tip", resourceCulture);
            }
        }
        
        internal static string ResetEcsCommand_Name {
            get {
                return ResourceManager.GetString("ResetEcsCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_EnableMouse_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_EnableMouse_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableECS_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECS_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_Mode_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Mode_Label", resourceCulture);
            }
        }
        
        internal static string OpenSettingsDialogCommand_TipTitle {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_TipTitle", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_MenuItemName {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_MenuItemName", resourceCulture);
            }
        }
        
        internal static string UnableToLaunchJzIntv_Error_Message_Format {
            get {
                return ResourceManager.GetString("UnableToLaunchJzIntv_Error_Message_Format", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_Failed_UnknownError_Format {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_UnknownError_Format", resourceCulture);
            }
        }
        
        internal static string SettingsPage_InputTabName {
            get {
                return ResourceManager.GetString("SettingsPage_InputTabName", resourceCulture);
            }
        }
        
        internal static string OpenSettingsDialogCommand_Name {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_Name", resourceCulture);
            }
        }
        
        internal static string ConfigurationFile_UnknownEmulatorFile_Error_Title {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownEmulatorFile_Error_Title", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_InitialKeyboardMap_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_InitialKeyboardMap_Tip", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Success_Title {
            get {
                return ResourceManager.GetString("SDLInstall_Success_Title", resourceCulture);
            }
        }
        
        internal static string JzIntvConfigurationStatus_Format {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_Format", resourceCulture);
            }
        }
        
        internal static string OpenSettingsDialogCommand_TipDescription {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_TipDescription", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_KeyboardHackfilePath_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick1Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick1Config_Label", resourceCulture);
            }
        }
        
        internal static string ClearClassicGameController1ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("ClearClassicGameController1ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        internal static string Select_CGC_Console_Prompt {
            get {
                return ResourceManager.GetString("Select_CGC_Console_Prompt", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Title {
            get {
                return ResourceManager.GetString("SDLInstall_Title", resourceCulture);
            }
        }
        
        internal static string ClearKeyboardConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("ClearKeyboardConfigFileCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_ResetJzIntvPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetJzIntvPath_Tip", resourceCulture);
            }
        }
        
        internal static string EnableFeature_UseRomSetting {
            get {
                return ResourceManager.GetString("EnableFeature_UseRomSetting", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_TipDescription {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_TipDescription", resourceCulture);
            }
        }
        
        internal static string LocateEcsCommand_Name {
            get {
                return ResourceManager.GetString("LocateEcsCommand_Name", resourceCulture);
            }
        }
        
        internal static string Locate_GROM_Prompt {
            get {
                return ResourceManager.GetString("Locate_GROM_Prompt", resourceCulture);
            }
        }
        
        internal static string JzIntvConfigurationStatus_MissingFilesFormat {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_MissingFilesFormat", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Failed_Format {
            get {
                return ResourceManager.GetString("SDLInstall_Failed_Format", resourceCulture);
            }
        }
        
        internal static string SelectClassicGameController0ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("SelectClassicGameController0ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        internal static string JzIntvConfigurationStatus_Ready {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_Ready", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_BrowseForGrom_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForGrom_Tip", resourceCulture);
            }
        }
        
        internal static string LaunchRibbonGroupCommand_Name {
            get {
                return ResourceManager.GetString("LaunchRibbonGroupCommand_Name", resourceCulture);
            }
        }
        
        internal static string ReportErrorDialogButtonText {
            get {
                return ResourceManager.GetString("ReportErrorDialogButtonText", resourceCulture);
            }
        }
        
        internal static string UnknownROM {
            get {
                return ResourceManager.GetString("UnknownROM", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_BrowseForJzIntv_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForJzIntv_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableEcs_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableEcs_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableECSKeyboardMap_Note {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECSKeyboardMap_Note", resourceCulture);
            }
        }
        
        internal static string SettingsPage_PathsTabName {
            get {
                return ResourceManager.GetString("SettingsPage_PathsTabName", resourceCulture);
            }
        }
        
        internal static string ConfigurationRibbonGroupCommand_Name_Format {
            get {
                return ResourceManager.GetString("ConfigurationRibbonGroupCommand_Name_Format", resourceCulture);
            }
        }
        
        internal static string CommandLineMode_Custom_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_Custom_DisplayName", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Name", resourceCulture);
            }
        }
        
        internal static string ShowInstalledDocumentsCommand_TipTitle {
            get {
                return ResourceManager.GetString("ShowInstalledDocumentsCommand_TipTitle", resourceCulture);
            }
        }
        
        internal static string Select_Hackfile_Prompt {
            get {
                return ResourceManager.GetString("Select_Hackfile_Prompt", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_Mode_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Mode_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableLocutus_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableLocutus_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_KeyboardHackfilePath_BrowseTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_BrowseTip", resourceCulture);
            }
        }
        
        internal static string ResetJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("ResetJzIntvCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Advanced_AdditionalArguments_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_AdditionalArguments_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_Resolution_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Resolution_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_ResetResolution_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_ResetResolution_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_BrowseForExec_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForExec_Tip", resourceCulture);
            }
        }
        
        internal static string ShowInstalledDocumentsCommand_Name {
            get {
                return ResourceManager.GetString("ShowInstalledDocumentsCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_Rom_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Rom_Hint", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_Grom_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Grom_Label", resourceCulture);
            }
        }
        
        internal static string ConfigurationRibbonGroupCommand_Name {
            get {
                return ResourceManager.GetString("ConfigurationRibbonGroupCommand_Name", resourceCulture);
            }
        }
        
        internal static string ShowInstalledDocumentsCommand_Tip {
            get {
                return ResourceManager.GetString("ShowInstalledDocumentsCommand_Tip", resourceCulture);
            }
        }
        
        internal static string AdvancedCommandGroupCommand_Name {
            get {
                return ResourceManager.GetString("AdvancedCommandGroupCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableIntellivoice_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableIntellivoice_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Advanced_UseRomSettingsWithCustomCommandLine_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_UseRomSettingsWithCustomCommandLine_Label", resourceCulture);
            }
        }
        
        internal static string EnableFeature_Always {
            get {
                return ResourceManager.GetString("EnableFeature_Always", resourceCulture);
            }
        }
        
        internal static string ConfigurationFile_UnknownEmulatorFile_Error_Message_Format {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownEmulatorFile_Error_Message_Format", resourceCulture);
            }
        }
        
        internal static string UnableToLaunchJzIntv_Error_Title {
            get {
                return ResourceManager.GetString("UnableToLaunchJzIntv_Error_Title", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick2Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick2Config_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Advanced_CustomCommandLine_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_CustomCommandLine_Hint", resourceCulture);
            }
        }
        
        internal static string ShowGettingStartedCommand_MenuItemName {
            get {
                return ResourceManager.GetString("ShowGettingStartedCommand_MenuItemName", resourceCulture);
            }
        }
        
        internal static string Configuration_EnableFullscreen {
            get {
                return ResourceManager.GetString("Configuration_EnableFullscreen", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_Failed_Title {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_Title", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Success_Message {
            get {
                return ResourceManager.GetString("SDLInstall_Success_Message", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick0Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick0Config_Hint", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_KeyboardHackfilePath_ClearTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_ClearTip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_JLPFeatures_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_JLPFeatures_Label", resourceCulture);
            }
        }
        
        internal static string Configuration_MuteSound_Tip {
            get {
                return ResourceManager.GetString("Configuration_MuteSound_Tip", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Update_Mounting {
            get {
                return ResourceManager.GetString("SDLInstall_Update_Mounting", resourceCulture);
            }
        }
        
        internal static string ResetGromCommand_Name {
            get {
                return ResourceManager.GetString("ResetGromCommand_Name", resourceCulture);
            }
        }
        
        internal static string CommandLineMode_Automatic_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_Automatic_DisplayName", resourceCulture);
            }
        }
        
        internal static string EnableFeature_Never {
            get {
                return ResourceManager.GetString("EnableFeature_Never", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Update_Unmounting {
            get {
                return ResourceManager.GetString("SDLInstall_Update_Unmounting", resourceCulture);
            }
        }
        
        internal static string ResetDisplayResolutionCommand_Name {
            get {
                return ResourceManager.GetString("ResetDisplayResolutionCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_GeneralTabName {
            get {
                return ResourceManager.GetString("SettingsPage_GeneralTabName", resourceCulture);
            }
        }
        
        internal static string SDLInstall_GeneralFailureMessage {
            get {
                return ResourceManager.GetString("SDLInstall_GeneralFailureMessage", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Failure_Title {
            get {
                return ResourceManager.GetString("SDLInstall_Failure_Title", resourceCulture);
            }
        }
        
        internal static string ShowInstalledDocumentsCommand_MenuItemName {
            get {
                return ResourceManager.GetString("ShowInstalledDocumentsCommand_MenuItemName", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_InitialKeyboardMap_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_InitialKeyboardMap_Label", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_Failed_KnownError_Format {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_KnownError_Format", resourceCulture);
            }
        }
        
        internal static string SDLInstall_UnableToGetUserLibraryDirectory {
            get {
                return ResourceManager.GetString("SDLInstall_UnableToGetUserLibraryDirectory", resourceCulture);
            }
        }
        
        internal static string ShowGettingStartedCommand_TipDescription {
            get {
                return ResourceManager.GetString("ShowGettingStartedCommand_TipDescription", resourceCulture);
            }
        }
        
        internal static string Locate_ECS_Prompt {
            get {
                return ResourceManager.GetString("Locate_ECS_Prompt", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_ResetResolution_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_ResetResolution_Tip", resourceCulture);
            }
        }
        
        internal static string LocateJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("LocateJzIntvCommand_Name", resourceCulture);
            }
        }
        
        internal static string BrowseAndLaunchInJzIntvCommand_TipDescription {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_TipDescription", resourceCulture);
            }
        }
        
        internal static string SDLInstall_UserLibraryDirectoryDoesNotExist_Format {
            get {
                return ResourceManager.GetString("SDLInstall_UserLibraryDirectoryDoesNotExist_Format", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick1Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick1Config_Hint", resourceCulture);
            }
        }
        
        internal static string BrowseAndLaunchInJzIntvCommand_Failed_Title {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_Failed_Title", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Update_Copying {
            get {
                return ResourceManager.GetString("SDLInstall_Update_Copying", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_JzIntv_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_JzIntv_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_DisplayTabName {
            get {
                return ResourceManager.GetString("SettingsPage_DisplayTabName", resourceCulture);
            }
        }
        
        internal static string SettingsPage_AdvancedTabName {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedTabName", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableJlp_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableJlp_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Advanced_AdditionalArguments_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_AdditionalArguments_Hint", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_JoystickConfigTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_JoystickConfigTip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_MuteSound_Label {
            get {
                return ResourceManager.GetString("SettingsPage_MuteSound_Label", resourceCulture);
            }
        }
        
        internal static string SDLNotFound_ErrorTitle {
            get {
                return ResourceManager.GetString("SDLNotFound_ErrorTitle", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick0Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick0Config_Label", resourceCulture);
            }
        }
        
        internal static string Select_CGC_ECS_Prompt {
            get {
                return ResourceManager.GetString("Select_CGC_ECS_Prompt", resourceCulture);
            }
        }
        
        internal static string SettingsPage_AllowMultipleInstances_Label {
            get {
                return ResourceManager.GetString("SettingsPage_AllowMultipleInstances_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        internal static string CommandLineMode_AutomaticWithAdditionalArguments_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_AutomaticWithAdditionalArguments_DisplayName", resourceCulture);
            }
        }
        
        internal static string OpenSettingsDialogCommand_MenuItemName {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_MenuItemName", resourceCulture);
            }
        }
        
        internal static string SDLNotFound_ErrorMessage {
            get {
                return ResourceManager.GetString("SDLNotFound_ErrorMessage", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_Failed_Message {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_Message", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick2Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick2Config_Hint", resourceCulture);
            }
        }
        
        internal static string SelectKeyboardConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("SelectKeyboardConfigFileCommand_Name", resourceCulture);
            }
        }
        
        internal static string Locate_jzIntv_Prompt {
            get {
                return ResourceManager.GetString("Locate_jzIntv_Prompt", resourceCulture);
            }
        }
        
        internal static string LaunchInJzIntvCommand_TipTitle {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_TipTitle", resourceCulture);
            }
        }
        
        internal static string ClearClassicGameController0ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("ClearClassicGameController0ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        internal static string JzIntv {
            get {
                return ResourceManager.GetString("JzIntv", resourceCulture);
            }
        }
        
        internal static string ConfigurationFile_UnknownSelection_Error_Title {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownSelection_Error_Title", resourceCulture);
            }
        }
        
        internal static string Locate_EXEC_Prompt {
            get {
                return ResourceManager.GetString("Locate_EXEC_Prompt", resourceCulture);
            }
        }
        
        internal static string BrowseAndLaunchInJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_Name", resourceCulture);
            }
        }
        
        internal static string LocateExecCommand_Name {
            get {
                return ResourceManager.GetString("LocateExecCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Advanced_CustomCommandLine_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_CustomCommandLine_Tip", resourceCulture);
            }
        }
        
        internal static string JzIntvConfigurationStatus_NotConfigured {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_NotConfigured", resourceCulture);
            }
        }
        
        internal static string BrowseAndLaunchInJzIntvCommand_Failed_MessageFormat {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_Failed_MessageFormat", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Display_Resolution_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Resolution_Tip", resourceCulture);
            }
        }
        
        internal static string ConfigurationFile_UnknownSelection_Error_Message_Format {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownSelection_Error_Message_Format", resourceCulture);
            }
        }
        
        internal static string SettingsPage_General_EnableECSKeyboardMap_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECSKeyboardMap_Label", resourceCulture);
            }
        }
        
        internal static string SelectClassicGameController1ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("SelectClassicGameController1ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        internal static string SDLInstall_Failed_Title {
            get {
                return ResourceManager.GetString("SDLInstall_Failed_Title", resourceCulture);
            }
        }
        
        internal static string SDLInstall_FailedToMount_Format {
            get {
                return ResourceManager.GetString("SDLInstall_FailedToMount_Format", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_BrowseForEcs_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForEcs_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_Ecs_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Ecs_Label", resourceCulture);
            }
        }
        
        internal static string LocateGromCommand_Name {
            get {
                return ResourceManager.GetString("LocateGromCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_Joystick3Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick3Config_Hint", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_JzIntv_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_JzIntv_Hint", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_Exec_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Exec_Label", resourceCulture);
            }
        }
        
        internal static string JzIntvAlreadyRunning {
            get {
                return ResourceManager.GetString("JzIntvAlreadyRunning", resourceCulture);
            }
        }
        
        internal static string ResetExecCommand_Name {
            get {
                return ResourceManager.GetString("ResetExecCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_ResetEcsPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetEcsPath_Tip", resourceCulture);
            }
        }
        
        internal static string ShowGettingStartedCommand_Name {
            get {
                return ResourceManager.GetString("ShowGettingStartedCommand_Name", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Advanced_UseRomSettingsNote_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_UseRomSettingsNote_Label", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Paths_ResetGromPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetGromPath_Tip", resourceCulture);
            }
        }
        
        internal static string Configuration_FullscreenMode_Tip {
            get {
                return ResourceManager.GetString("Configuration_FullscreenMode_Tip", resourceCulture);
            }
        }
        
        internal static string SettingsPage_Input_KeyboardHackfilePath_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_Hint", resourceCulture);
            }
        }
    }
}
