//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTV.JzIntvUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INTV.jzIntvUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically generate command line.
        /// </summary>
        internal static string CommandLineMode_Automatic_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_Automatic_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically generate with additional arguments.
        /// </summary>
        internal static string CommandLineMode_AutomaticWithAdditionalArguments_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_AutomaticWithAdditionalArguments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom command line.
        /// </summary>
        internal static string CommandLineMode_Custom_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_Custom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string EnableFeature_Always {
            get {
                return ResourceManager.GetString("EnableFeature_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string EnableFeature_Never {
            get {
                return ResourceManager.GetString("EnableFeature_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ROM Setting.
        /// </summary>
        internal static string EnableFeature_UseRomSetting {
            get {
                return ResourceManager.GetString("EnableFeature_UseRomSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional arguments.
        /// </summary>
        internal static string SettingsPage_Advanced_AdditionalArguments_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_AdditionalArguments_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide command line arguments to use in addition to the automatically generated arguments.
        /// </summary>
        internal static string SettingsPage_Advanced_AdditionalArguments_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_AdditionalArguments_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom command line.
        /// </summary>
        internal static string SettingsPage_Advanced_CustomCommandLine_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_CustomCommandLine_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply your own command line arguments; only the ROM path and, optionally, ROM-specific arguments will be generated automatically.
        /// </summary>
        internal static string SettingsPage_Advanced_CustomCommandLine_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_CustomCommandLine_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: This will add settings based on ROM features if so configured in General settings.
        /// </summary>
        internal static string SettingsPage_Advanced_UseRomSettingsNote_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_UseRomSettingsNote_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use settings defined by ROM.
        /// </summary>
        internal static string SettingsPage_Advanced_UseRomSettingsWithCustomCommandLine_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_UseRomSettingsWithCustomCommandLine_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsPage_AdvancedTabName {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple copies to run.
        /// </summary>
        internal static string SettingsPage_AllowMultipleInstances_Label {
            get {
                return ResourceManager.GetString("SettingsPage_AllowMultipleInstances_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mouse.
        /// </summary>
        internal static string SettingsPage_Display_EnableMouse_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_EnableMouse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string SettingsPage_Display_Mode_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Mode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the display mode to use.
        /// </summary>
        internal static string SettingsPage_Display_Mode_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Mode_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsPage_Display_ResetResolution_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_ResetResolution_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to the default screen resolution.
        /// </summary>
        internal static string SettingsPage_Display_ResetResolution_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_ResetResolution_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Resolution.
        /// </summary>
        internal static string SettingsPage_Display_Resolution_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Resolution_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the screen resolution to use.
        /// </summary>
        internal static string SettingsPage_Display_Resolution_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Resolution_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SettingsPage_DisplayTabName {
            get {
                return ResourceManager.GetString("SettingsPage_DisplayTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ECS.
        /// </summary>
        internal static string SettingsPage_General_EnableECS_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable ECS emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableEcs_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableEcs_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ECS keyboard map for ECS ROMs.
        /// </summary>
        internal static string SettingsPage_General_EnableECSKeyboardMap_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECSKeyboardMap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: This may override initial keyboard map setting.
        /// </summary>
        internal static string SettingsPage_General_EnableECSKeyboardMap_Note {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECSKeyboardMap_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Intellivoice.
        /// </summary>
        internal static string SettingsPage_General_EnableIntellivoice_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableIntellivoice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable Intellivoice emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableIntellivoice_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableIntellivoice_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable JLP emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableJlp_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableJlp_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable LTO Flash! emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableLocutus_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableLocutus_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP Features.
        /// </summary>
        internal static string SettingsPage_General_JLPFeatures_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_JLPFeatures_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsPage_GeneralTabName {
            get {
                return ResourceManager.GetString("SettingsPage_GeneralTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Keyboard Map.
        /// </summary>
        internal static string SettingsPage_Input_InitialKeyboardMap_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_InitialKeyboardMap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select initial keyboard map to use.
        /// </summary>
        internal static string SettingsPage_Input_InitialKeyboardMap_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_InitialKeyboardMap_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 1 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick0Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick0Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 1.
        /// </summary>
        internal static string SettingsPage_Input_Joystick0Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick0Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 2 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick1Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick1Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 2.
        /// </summary>
        internal static string SettingsPage_Input_Joystick1Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick1Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 3 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick2Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick2Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 3.
        /// </summary>
        internal static string SettingsPage_Input_Joystick2Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick2Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 4 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick3Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick3Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 4.
        /// </summary>
        internal static string SettingsPage_Input_Joystick3Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick3Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide configuration for a joystick.
        /// </summary>
        internal static string SettingsPage_Input_JoystickConfigTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_JoystickConfigTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select keyboard hackfile.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_BrowseTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_BrowseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset keyboard hackfile.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_ClearTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_ClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard hackfile.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string SettingsPage_InputTabName {
            get {
                return ResourceManager.GetString("SettingsPage_InputTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute sound.
        /// </summary>
        internal static string SettingsPage_MuteSound_Label {
            get {
                return ResourceManager.GetString("SettingsPage_MuteSound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the ECS ROM.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForEcs_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForEcs_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the EXEC ROM.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForExec_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForExec_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the GROM ROM.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForGrom_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForGrom_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the jzIntv emulator program.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForJzIntv_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForJzIntv_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS.
        /// </summary>
        internal static string SettingsPage_Paths_Ecs_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Ecs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC.
        /// </summary>
        internal static string SettingsPage_Paths_Exec_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Exec_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROM.
        /// </summary>
        internal static string SettingsPage_Paths_Grom_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Grom_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv Emulator Path.
        /// </summary>
        internal static string SettingsPage_Paths_JzIntv_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_JzIntv_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv.
        /// </summary>
        internal static string SettingsPage_Paths_JzIntv_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_JzIntv_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the ECS ROM path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetEcsPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetEcsPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the EXEC ROM path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetExecPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetExecPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the GROM ROM path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetGromPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetGromPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the jzIntv emulator path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetJzIntvPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetJzIntvPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: jzIntv Directory.
        /// </summary>
        internal static string SettingsPage_Paths_Rom_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Rom_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string SettingsPage_PathsTabName {
            get {
                return ResourceManager.GetString("SettingsPage_PathsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
    }
}
