//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTV.JzIntvUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INTV.jzIntvUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedCommandGroupCommand_Name {
            get {
                return ResourceManager.GetString("AdvancedCommandGroupCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file:
        ///
        ///{0}
        ///
        ///does not appear to be a valid ROM file..
        /// </summary>
        internal static string BrowseAndLaunchInJzIntvCommand_Failed_MessageFormat {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_Failed_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Launch.
        /// </summary>
        internal static string BrowseAndLaunchInJzIntvCommand_Failed_Title {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse &amp; Play in jzIntv....
        /// </summary>
        internal static string BrowseAndLaunchInJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to select a ROM, then run it in the jzIntv emulator..
        /// </summary>
        internal static string BrowseAndLaunchInJzIntvCommand_TipDescription {
            get {
                return ResourceManager.GetString("BrowseAndLaunchInJzIntvCommand_TipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Classic Game Controller 0 (Master Component) Configuration File.
        /// </summary>
        internal static string ClearClassicGameController0ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("ClearClassicGameController0ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Classic Game Controller 1 (ECS) Configuration File.
        /// </summary>
        internal static string ClearClassicGameController1ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("ClearClassicGameController1ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Default Keyboard Hackfile.
        /// </summary>
        internal static string ClearKeyboardConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("ClearKeyboardConfigFileCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically generate command line.
        /// </summary>
        internal static string CommandLineMode_Automatic_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_Automatic_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically generate with additional arguments.
        /// </summary>
        internal static string CommandLineMode_AutomaticWithAdditionalArguments_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_AutomaticWithAdditionalArguments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom command line.
        /// </summary>
        internal static string CommandLineMode_Custom_DisplayName {
            get {
                return ResourceManager.GetString("CommandLineMode_Custom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in fullscreen mode.
        /// </summary>
        internal static string Configuration_EnableFullscreen {
            get {
                return ResourceManager.GetString("Configuration_EnableFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, run jzIntv in fullscreen mode.
        /// </summary>
        internal static string Configuration_FullscreenMode_Tip {
            get {
                return ResourceManager.GetString("Configuration_FullscreenMode_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, sound is disabled in jzIntv.
        /// </summary>
        internal static string Configuration_MuteSound_Tip {
            get {
                return ResourceManager.GetString("Configuration_MuteSound_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested to clear unrecognized emulator file: {0}.
        /// </summary>
        internal static string ConfigurationFile_UnknownEmulatorFile_Error_Message_Format {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownEmulatorFile_Error_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Emulator File.
        /// </summary>
        internal static string ConfigurationFile_UnknownEmulatorFile_Error_Title {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownEmulatorFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested to select unrecognized file: {0}.
        /// </summary>
        internal static string ConfigurationFile_UnknownSelection_Error_Message_Format {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownSelection_Error_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized File Selection.
        /// </summary>
        internal static string ConfigurationFile_UnknownSelection_Error_Title {
            get {
                return ResourceManager.GetString("ConfigurationFile_UnknownSelection_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationRibbonGroupCommand_Name {
            get {
                return ResourceManager.GetString("ConfigurationRibbonGroupCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration: {0}.
        /// </summary>
        internal static string ConfigurationRibbonGroupCommand_Name_Format {
            get {
                return ResourceManager.GetString("ConfigurationRibbonGroupCommand_Name_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string EnableFeature_Always {
            get {
                return ResourceManager.GetString("EnableFeature_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string EnableFeature_Never {
            get {
                return ResourceManager.GetString("EnableFeature_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ROM Setting.
        /// </summary>
        internal static string EnableFeature_UseRomSetting {
            get {
                return ResourceManager.GetString("EnableFeature_UseRomSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv.
        /// </summary>
        internal static string JzIntv {
            get {
                return ResourceManager.GetString("JzIntv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of jzIntv is already running!.
        /// </summary>
        internal static string JzIntvAlreadyRunning {
            get {
                return ResourceManager.GetString("JzIntvAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv Configuration: {0}.
        /// </summary>
        internal static string JzIntvConfigurationStatus_Format {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing: {0}.
        /// </summary>
        internal static string JzIntvConfigurationStatus_MissingFilesFormat {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_MissingFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Configured.
        /// </summary>
        internal static string JzIntvConfigurationStatus_NotConfigured {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string JzIntvConfigurationStatus_Ready {
            get {
                return ResourceManager.GetString("JzIntvConfigurationStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv is unable to run &apos;{0}&apos;.
        ///The error message was:
        ///
        ///{1}.
        /// </summary>
        internal static string LaunchInJzIntvCommand_Failed_KnownError_Format {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_KnownError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred running jzIntv..
        /// </summary>
        internal static string LaunchInJzIntvCommand_Failed_Message {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzInv Error.
        /// </summary>
        internal static string LaunchInJzIntvCommand_Failed_Title {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv is unable to run &apos;{0}&apos;. No further information is available..
        /// </summary>
        internal static string LaunchInJzIntvCommand_Failed_UnknownError_Format {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Failed_UnknownError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play in jzIntv.
        /// </summary>
        internal static string LaunchInJzIntvCommand_MenuItemName {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_MenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string LaunchInJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the selected ROM using the jzIntv emulator.
        /// </summary>
        internal static string LaunchInJzIntvCommand_TipDescription {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_TipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play in jzIntv.
        /// </summary>
        internal static string LaunchInJzIntvCommand_TipTitle {
            get {
                return ResourceManager.GetString("LaunchInJzIntvCommand_TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM.
        /// </summary>
        internal static string LaunchRibbonGroupCommand_Name {
            get {
                return ResourceManager.GetString("LaunchRibbonGroupCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate ECS.
        /// </summary>
        internal static string Locate_ECS_Prompt {
            get {
                return ResourceManager.GetString("Locate_ECS_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate EXEC.
        /// </summary>
        internal static string Locate_EXEC_Prompt {
            get {
                return ResourceManager.GetString("Locate_EXEC_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate GROM.
        /// </summary>
        internal static string Locate_GROM_Prompt {
            get {
                return ResourceManager.GetString("Locate_GROM_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate jzIntv.
        /// </summary>
        internal static string Locate_jzIntv_Prompt {
            get {
                return ResourceManager.GetString("Locate_jzIntv_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate ECS ROM File.
        /// </summary>
        internal static string LocateEcsCommand_Name {
            get {
                return ResourceManager.GetString("LocateEcsCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate EXEC ROM.
        /// </summary>
        internal static string LocateExecCommand_Name {
            get {
                return ResourceManager.GetString("LocateExecCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate GROM ROM File.
        /// </summary>
        internal static string LocateGromCommand_Name {
            get {
                return ResourceManager.GetString("LocateGromCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate jzIntv.
        /// </summary>
        internal static string LocateJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("LocateJzIntvCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string OpenSettingsDialogCommand_Name {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure jzIntv settings.
        /// </summary>
        internal static string OpenSettingsDialogCommand_TipDescription {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_TipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv Settings.
        /// </summary>
        internal static string OpenSettingsDialogCommand_TipTitle {
            get {
                return ResourceManager.GetString("OpenSettingsDialogCommand_TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReportErrorDialogButtonText {
            get {
                return ResourceManager.GetString("ReportErrorDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Resolution.
        /// </summary>
        internal static string ResetDisplayResolutionCommand_Name {
            get {
                return ResourceManager.GetString("ResetDisplayResolutionCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset ECS ROM File Location.
        /// </summary>
        internal static string ResetEcsCommand_Name {
            get {
                return ResourceManager.GetString("ResetEcsCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset EXEC ROM File Location.
        /// </summary>
        internal static string ResetExecCommand_Name {
            get {
                return ResourceManager.GetString("ResetExecCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset GROM ROM File Location.
        /// </summary>
        internal static string ResetGromCommand_Name {
            get {
                return ResourceManager.GetString("ResetGromCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset jzIntv Location.
        /// </summary>
        internal static string ResetJzIntvCommand_Name {
            get {
                return ResourceManager.GetString("ResetJzIntvCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &quot;hackfile&quot; for Classic Game Controller 1 (Master Component).
        /// </summary>
        internal static string Select_CGC_Console_Prompt {
            get {
                return ResourceManager.GetString("Select_CGC_Console_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &quot;hackfile&quot; for Classic Game Controller 2 (ECS).
        /// </summary>
        internal static string Select_CGC_ECS_Prompt {
            get {
                return ResourceManager.GetString("Select_CGC_ECS_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a keyboard &quot;hackfile&quot;.
        /// </summary>
        internal static string Select_Hackfile_Prompt {
            get {
                return ResourceManager.GetString("Select_Hackfile_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Classic Game Controller 0 (Master Component) Configuration File.
        /// </summary>
        internal static string SelectClassicGameController0ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("SelectClassicGameController0ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Classic Game Controller 1 (ECS) Configuration File.
        /// </summary>
        internal static string SelectClassicGameController1ConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("SelectClassicGameController1ConfigFileCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Keyboard Hackfile.
        /// </summary>
        internal static string SelectKeyboardConfigFileCommand_Name {
            get {
                return ResourceManager.GetString("SelectKeyboardConfigFileCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional arguments.
        /// </summary>
        internal static string SettingsPage_Advanced_AdditionalArguments_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_AdditionalArguments_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide command line arguments to use in addition to the automatically generated arguments.
        /// </summary>
        internal static string SettingsPage_Advanced_AdditionalArguments_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_AdditionalArguments_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom command line.
        /// </summary>
        internal static string SettingsPage_Advanced_CustomCommandLine_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_CustomCommandLine_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply your own command line arguments; only the ROM path and, optionally, ROM-specific arguments will be generated automatically.
        /// </summary>
        internal static string SettingsPage_Advanced_CustomCommandLine_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_CustomCommandLine_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: This will add settings based on ROM features if so configured in General settings.
        /// </summary>
        internal static string SettingsPage_Advanced_UseRomSettingsNote_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_UseRomSettingsNote_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use settings defined by ROM.
        /// </summary>
        internal static string SettingsPage_Advanced_UseRomSettingsWithCustomCommandLine_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Advanced_UseRomSettingsWithCustomCommandLine_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsPage_AdvancedTabName {
            get {
                return ResourceManager.GetString("SettingsPage_AdvancedTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple copies to run.
        /// </summary>
        internal static string SettingsPage_AllowMultipleInstances_Label {
            get {
                return ResourceManager.GetString("SettingsPage_AllowMultipleInstances_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mouse.
        /// </summary>
        internal static string SettingsPage_Display_EnableMouse_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_EnableMouse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string SettingsPage_Display_Mode_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Mode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the display mode to use.
        /// </summary>
        internal static string SettingsPage_Display_Mode_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Mode_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsPage_Display_ResetResolution_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_ResetResolution_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to the default screen resolution.
        /// </summary>
        internal static string SettingsPage_Display_ResetResolution_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_ResetResolution_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Resolution.
        /// </summary>
        internal static string SettingsPage_Display_Resolution_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Resolution_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the screen resolution to use.
        /// </summary>
        internal static string SettingsPage_Display_Resolution_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Display_Resolution_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SettingsPage_DisplayTabName {
            get {
                return ResourceManager.GetString("SettingsPage_DisplayTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ECS.
        /// </summary>
        internal static string SettingsPage_General_EnableECS_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable ECS emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableEcs_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableEcs_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ECS keyboard map for ECS ROMs.
        /// </summary>
        internal static string SettingsPage_General_EnableECSKeyboardMap_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECSKeyboardMap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: This may override initial keyboard map setting.
        /// </summary>
        internal static string SettingsPage_General_EnableECSKeyboardMap_Note {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableECSKeyboardMap_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Intellivoice.
        /// </summary>
        internal static string SettingsPage_General_EnableIntellivoice_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableIntellivoice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable Intellivoice emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableIntellivoice_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableIntellivoice_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable JLP emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableJlp_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableJlp_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the policy used to enable LTO Flash! emulation.
        /// </summary>
        internal static string SettingsPage_General_EnableLocutus_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_General_EnableLocutus_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP Features.
        /// </summary>
        internal static string SettingsPage_General_JLPFeatures_Label {
            get {
                return ResourceManager.GetString("SettingsPage_General_JLPFeatures_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsPage_GeneralTabName {
            get {
                return ResourceManager.GetString("SettingsPage_GeneralTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Keyboard Map.
        /// </summary>
        internal static string SettingsPage_Input_InitialKeyboardMap_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_InitialKeyboardMap_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select initial keyboard map to use.
        /// </summary>
        internal static string SettingsPage_Input_InitialKeyboardMap_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_InitialKeyboardMap_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 1 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick0Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick0Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 1.
        /// </summary>
        internal static string SettingsPage_Input_Joystick0Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick0Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 2 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick1Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick1Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 2.
        /// </summary>
        internal static string SettingsPage_Input_Joystick1Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick1Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 3 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick2Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick2Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 3.
        /// </summary>
        internal static string SettingsPage_Input_Joystick2Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick2Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 4 configuration.
        /// </summary>
        internal static string SettingsPage_Input_Joystick3Config_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick3Config_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick 4.
        /// </summary>
        internal static string SettingsPage_Input_Joystick3Config_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_Joystick3Config_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide configuration for a joystick.
        /// </summary>
        internal static string SettingsPage_Input_JoystickConfigTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_JoystickConfigTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select keyboard hackfile.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_BrowseTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_BrowseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset keyboard hackfile.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_ClearTip {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_ClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard hackfile.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string SettingsPage_Input_KeyboardHackfilePath_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Input_KeyboardHackfilePath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string SettingsPage_InputTabName {
            get {
                return ResourceManager.GetString("SettingsPage_InputTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute sound.
        /// </summary>
        internal static string SettingsPage_MuteSound_Label {
            get {
                return ResourceManager.GetString("SettingsPage_MuteSound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the ECS ROM.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForEcs_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForEcs_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the EXEC ROM.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForExec_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForExec_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the GROM ROM.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForGrom_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForGrom_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the jzIntv emulator program.
        /// </summary>
        internal static string SettingsPage_Paths_BrowseForJzIntv_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_BrowseForJzIntv_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS.
        /// </summary>
        internal static string SettingsPage_Paths_Ecs_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Ecs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC.
        /// </summary>
        internal static string SettingsPage_Paths_Exec_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Exec_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROM.
        /// </summary>
        internal static string SettingsPage_Paths_Grom_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Grom_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv Emulator Path.
        /// </summary>
        internal static string SettingsPage_Paths_JzIntv_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_JzIntv_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv.
        /// </summary>
        internal static string SettingsPage_Paths_JzIntv_Label {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_JzIntv_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the ECS ROM path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetEcsPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetEcsPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the EXEC ROM path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetExecPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetExecPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the GROM ROM path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetGromPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetGromPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the jzIntv emulator path.
        /// </summary>
        internal static string SettingsPage_Paths_ResetJzIntvPath_Tip {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_ResetJzIntvPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: jzIntv Directory.
        /// </summary>
        internal static string SettingsPage_Paths_Rom_Hint {
            get {
                return ResourceManager.GetString("SettingsPage_Paths_Rom_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        internal static string SettingsPage_PathsTabName {
            get {
                return ResourceManager.GetString("SettingsPage_PathsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jzIntv.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch jzIntv to run &apos;{0}&apos;.
        ///The error message was:
        ///
        ///{1}.
        /// </summary>
        internal static string UnableToLaunchJzIntv_Error_Message_Format {
            get {
                return ResourceManager.GetString("UnableToLaunchJzIntv_Error_Message_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Launching jzInv.
        /// </summary>
        internal static string UnableToLaunchJzIntv_Error_Title {
            get {
                return ResourceManager.GetString("UnableToLaunchJzIntv_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown Program&gt;.
        /// </summary>
        internal static string UnknownROM {
            get {
                return ResourceManager.GetString("UnknownROM", resourceCulture);
            }
        }
    }
}
