//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTV.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INTV.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRC value of a program may not be zero..
        /// </summary>
        internal static string CrcData_InvalidCRC {
            get {
                return ResourceManager.GetString("CrcData_InvalidCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP03.
        /// </summary>
        internal static string JlpHardwareVersion_03 {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP04.
        /// </summary>
        internal static string JlpHardwareVersion_04 {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP05.
        /// </summary>
        internal static string JlpHardwareVersion_05 {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible.
        /// </summary>
        internal static string JlpHardwareVersion_Incompatible {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string JlpHardwareVersion_None {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ProgramInformation_DefaultTitle {
            get {
                return ResourceManager.GetString("ProgramInformation_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected LUIGI version: {0}. Check for an updated version of the software..
        /// </summary>
        internal static string UnsupportedLuigiVersion_Format {
            get {
                return ResourceManager.GetString("UnsupportedLuigiVersion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRC value of a program may not be zero..
        /// </summary>
        internal static string UserSpecifiedProgramInformation_AddInvalidCRCMessage {
            get {
                return ResourceManager.GetString("UserSpecifiedProgramInformation_AddInvalidCRCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nonzero CRC value is necessary to create a Program Information entry..
        /// </summary>
        internal static string UserSpecifiedProgramInformation_CreatedWithInvalidCRCMessage {
            get {
                return ResourceManager.GetString("UserSpecifiedProgramInformation_CreatedWithInvalidCRCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to modify an invalid Program Information entry..
        /// </summary>
        internal static string UserSpecifiedProgramInformation_CreatedWithInvalidSource {
            get {
                return ResourceManager.GetString("UserSpecifiedProgramInformation_CreatedWithInvalidSource", resourceCulture);
            }
        }
    }
}
