//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTV.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INTV.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website for {0}: {1}.
        /// </summary>
        internal static string AdditionalVendorInfoWebsite_Format {
            get {
                return ResourceManager.GetString("AdditionalVendorInfoWebsite_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert CfgVarMetadataIdTag to LuigiMetadataIdTag!.
        /// </summary>
        internal static string CfgVarMetadata_ToLuigiError {
            get {
                return ResourceManager.GetString("CfgVarMetadata_ToLuigiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert CfgVarMetadataIdTag to RomMetadataIdTag!.
        /// </summary>
        internal static string CfgVarMetadata_ToRomError {
            get {
                return ResourceManager.GetString("CfgVarMetadata_ToRomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFGVAR type is not a FeatureCompatibility type: {0}.
        /// </summary>
        internal static string CfgVarMetadata_TypeError {
            get {
                return ResourceManager.GetString("CfgVarMetadata_TypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adjacent input range for the 16 disc directions must be less than 8..
        /// </summary>
        internal static string ControllerKeys_AdjacentDistanceTooLarge {
            get {
                return ResourceManager.GetString("ControllerKeys_AdjacentDistanceTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRC value of a program may not be zero..
        /// </summary>
        internal static string CrcData_InvalidCRC {
            get {
                return ResourceManager.GetString("CrcData_InvalidCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to create LUIGI feature flags for unsupported FeatureCategory: {0}.
        /// </summary>
        internal static string FeatureCategoryNotSupportedByLuigiFormat {
            get {
                return ResourceManager.GetString("FeatureCategoryNotSupportedByLuigiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data block checksum.
        ///  Expected: {0}
        ///  Actual: {1}.
        /// </summary>
        internal static string InvalidDataBlockChecksumFormat {
            get {
                return ResourceManager.GetString("InvalidDataBlockChecksumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LUIGI header size: {0}.
        /// </summary>
        internal static string InvalidLuigiHeaderSizeFormat {
            get {
                return ResourceManager.GetString("InvalidLuigiHeaderSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP03.
        /// </summary>
        internal static string JlpHardwareVersion_03 {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP04.
        /// </summary>
        internal static string JlpHardwareVersion_04 {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLP05.
        /// </summary>
        internal static string JlpHardwareVersion_05 {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible.
        /// </summary>
        internal static string JlpHardwareVersion_Incompatible {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string JlpHardwareVersion_None {
            get {
                return ResourceManager.GetString("JlpHardwareVersion_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate ROM paths do not also provide alternate .cfg file paths!.
        /// </summary>
        internal static string ProgramDescription_MissingAlternateCfgFile {
            get {
                return ResourceManager.GetString("ProgramDescription_MissingAlternateCfgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ProgramInformation_DefaultTitle {
            get {
                return ResourceManager.GetString("ProgramInformation_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected ProgramInformation field: {0}.
        /// </summary>
        internal static string ProgramInformation_InvalidFieldFormat {
            get {
                return ResourceManager.GetString("ProgramInformation_InvalidFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding entries to the default database is not permitted..
        /// </summary>
        internal static string ProgramInformationTable_NoEditsToDefaultDatabase {
            get {
                return ResourceManager.GetString("ProgramInformationTable_NoEditsToDefaultDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid program ROM information. The following fields are not valid:.
        /// </summary>
        internal static string ProgramRomValidationFailed_Message {
            get {
                return ResourceManager.GetString("ProgramRomValidationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-ROM object was passed to RomComparer.Compare().
        /// </summary>
        internal static string RomComparer_InvalidArgument_NonRom {
            get {
                return ResourceManager.GetString("RomComparer_InvalidArgument_NonRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-ROM objects were passed to RomComparer.Compare().
        /// </summary>
        internal static string RomComparer_InvalidArguments_NonRom {
            get {
                return ResourceManager.GetString("RomComparer_InvalidArguments_NonRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ROM comparison requested: {0}.
        /// </summary>
        internal static string RomComparer_InvalidCompareRequestedFormat {
            get {
                return ResourceManager.GetString("RomComparer_InvalidCompareRequestedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ROM file - it is not .rom or .cc3 format..
        /// </summary>
        internal static string RomFormatRom_InvalidFormat {
            get {
                return ResourceManager.GetString("RomFormatRom_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize ROM metadata payload!.
        /// </summary>
        internal static string RomMetadata_FailedToDeserializePayload {
            get {
                return ResourceManager.GetString("RomMetadata_FailedToDeserializePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ROM metadata type passed to RomMetadataDate: {0}.
        /// </summary>
        internal static string RomMetadataDate_InvalidMetadataIdFormat {
            get {
                return ResourceManager.GetString("RomMetadataDate_InvalidMetadataIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected LUIGI version: {0}. Check for an updated version of the software..
        /// </summary>
        internal static string UnsupportedLuigiVersion_Format {
            get {
                return ResourceManager.GetString("UnsupportedLuigiVersion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRC value of a program may not be zero..
        /// </summary>
        internal static string UserSpecifiedProgramInformation_AddInvalidCRCMessage {
            get {
                return ResourceManager.GetString("UserSpecifiedProgramInformation_AddInvalidCRCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nonzero CRC value is necessary to create a Program Information entry..
        /// </summary>
        internal static string UserSpecifiedProgramInformation_CreatedWithInvalidCRCMessage {
            get {
                return ResourceManager.GetString("UserSpecifiedProgramInformation_CreatedWithInvalidCRCMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to modify an invalid Program Information entry..
        /// </summary>
        internal static string UserSpecifiedProgramInformation_CreatedWithInvalidSource {
            get {
                return ResourceManager.GetString("UserSpecifiedProgramInformation_CreatedWithInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converter for column &apos;{0}&apos; expected data type &apos;{1}&apos; but received a result of type &apos;{2}&apos;..
        /// </summary>
        internal static string XmlRomInformationColumnConverter_IncompatibleConverterFormat {
            get {
                return ResourceManager.GetString("XmlRomInformationColumnConverter_IncompatibleConverterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column named &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string XmlRomInformationColumnConverter_InvalidColumnFormat {
            get {
                return ResourceManager.GetString("XmlRomInformationColumnConverter_InvalidColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate data converter for column &apos;{0}&apos;..
        /// </summary>
        internal static string XmlRomInformationColumnConverter_InvalidConverterFormat {
            get {
                return ResourceManager.GetString("XmlRomInformationColumnConverter_InvalidConverterFormat", resourceCulture);
            }
        }
    }
}
