//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTV.LtoFlash.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public double MenuLayoutLongNameColWidth {
            get {
                return ((double)(this["MenuLayoutLongNameColWidth"]));
            }
            set {
                this["MenuLayoutLongNameColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public double MenuLayoutShortNameColWidth {
            get {
                return ((double)(this["MenuLayoutShortNameColWidth"]));
            }
            set {
                this["MenuLayoutShortNameColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public double MenuLayoutManualColWidth {
            get {
                return ((double)(this["MenuLayoutManualColWidth"]));
            }
            set {
                this["MenuLayoutManualColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public double MenuLayoutSaveDataColWidth {
            get {
                return ((double)(this["MenuLayoutSaveDataColWidth"]));
            }
            set {
                this["MenuLayoutSaveDataColWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("384")]
        public double MenuLayoutWidth {
            get {
                return ((double)(this["MenuLayoutWidth"]));
            }
            set {
                this["MenuLayoutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ValidateMenuAtStartup {
            get {
                return ((bool)(this["ValidateMenuAtStartup"]));
            }
            set {
                this["ValidateMenuAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchForDevicesAtStartup {
            get {
                return ((bool)(this["SearchForDevicesAtStartup"]));
            }
            set {
                this["SearchForDevicesAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReconcileDeviceMenuWithLocalMenu {
            get {
                return ((bool)(this["ReconcileDeviceMenuWithLocalMenu"]));
            }
            set {
                this["ReconcileDeviceMenuWithLocalMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedFeatures {
            get {
                return ((bool)(this["ShowAdvancedFeatures"]));
            }
            set {
                this["ShowAdvancedFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastActiveDevicePort {
            get {
                return ((string)(this["LastActiveDevicePort"]));
            }
            set {
                this["LastActiveDevicePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunGCWhenConnected {
            get {
                return ((bool)(this["RunGCWhenConnected"]));
            }
            set {
                this["RunGCWhenConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticallyConnectToDevices {
            get {
                return ((bool)(this["AutomaticallyConnectToDevices"]));
            }
            set {
                this["AutomaticallyConnectToDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptToAddRomsToMenu {
            get {
                return ((bool)(this["PromptToAddRomsToMenu"]));
            }
            set {
                this["PromptToAddRomsToMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddRomsToMenu {
            get {
                return ((bool)(this["AddRomsToMenu"]));
            }
            set {
                this["AddRomsToMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFileSystemDetails {
            get {
                return ((bool)(this["ShowFileSystemDetails"]));
            }
            set {
                this["ShowFileSystemDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnablePortLogging {
            get {
                return ((bool)(this["EnablePortLogging"]));
            }
            set {
                this["EnablePortLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptToInstallFTDIDriver {
            get {
                return ((bool)(this["PromptToInstallFTDIDriver"]));
            }
            set {
                this["PromptToInstallFTDIDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptToImportStarterRoms {
            get {
                return ((bool)(this["PromptToImportStarterRoms"]));
            }
            set {
                this["PromptToImportStarterRoms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptForFirmwareUpgrade {
            get {
                return ((bool)(this["PromptForFirmwareUpgrade"]));
            }
            set {
                this["PromptForFirmwareUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerifyVIDandPIDBeforeConnecting {
            get {
                return ((bool)(this["VerifyVIDandPIDBeforeConnecting"]));
            }
            set {
                this["VerifyVIDandPIDBeforeConnecting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreventSystemSleepDuringDeviceCommands {
            get {
                return ((bool)(this["PreventSystemSleepDuringDeviceCommands"]));
            }
            set {
                this["PreventSystemSleepDuringDeviceCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LtoFlashSerialReadChunkSize {
            get {
                return ((int)(this["LtoFlashSerialReadChunkSize"]));
            }
            set {
                this["LtoFlashSerialReadChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LtoFlashSerialWriteChunkSize {
            get {
                return ((int)(this["LtoFlashSerialWriteChunkSize"]));
            }
            set {
                this["LtoFlashSerialWriteChunkSize"] = value;
            }
        }
    }
}
