
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.LtoFlash.View
{
	public partial class PromptToAddMenuItemsForNewRoms
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label _message;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.VBox vbox5;

		private global::Gtk.CheckButton _addToMenu;

		private global::Gtk.CheckButton _doNotAskAgain;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget INTV.LtoFlash.View.PromptToAddMenuItemsForNewRoms
			this.Name = "INTV.LtoFlash.View.PromptToAddMenuItemsForNewRoms";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child INTV.LtoFlash.View.PromptToAddMenuItemsForNewRoms.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(4));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this._message = new global::Gtk.Label();
			this._message.Name = "_message";
			this._message.Xalign = 0F;
			this._message.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this._message.Wrap = true;
			this.vbox2.Add(this._message);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this._message]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(2));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hbox2.Add(this.alignment3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment3]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this._addToMenu = new global::Gtk.CheckButton();
			this._addToMenu.CanFocus = true;
			this._addToMenu.Name = "_addToMenu";
			this._addToMenu.Label = global::Mono.Unix.Catalog.GetString("checkbutton9");
			this._addToMenu.DrawIndicator = true;
			this._addToMenu.UseUnderline = true;
			this._addToMenu.Xalign = 1F;
			this.vbox5.Add(this._addToMenu);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this._addToMenu]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this._doNotAskAgain = new global::Gtk.CheckButton();
			this._doNotAskAgain.CanFocus = true;
			this._doNotAskAgain.Name = "_doNotAskAgain";
			this._doNotAskAgain.Label = global::Mono.Unix.Catalog.GetString("checkbutton10");
			this._doNotAskAgain.DrawIndicator = true;
			this._doNotAskAgain.UseUnderline = true;
			this._doNotAskAgain.Xalign = 1F;
			this.vbox5.Add(this._doNotAskAgain);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this._doNotAskAgain]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox2.Add(this.vbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox5]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			w6.Expand = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w7.Position = 1;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w8.Position = 0;
			// Internal child INTV.LtoFlash.View.PromptToAddMenuItemsForNewRoms.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonOk]));
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this._addToMenu.Toggled += new global::System.EventHandler(this.HandleAddToMenuToggled);
			this._doNotAskAgain.Toggled += new global::System.EventHandler(this.HandleDoNotAskToggled);
		}
	}
}
