
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.LtoFlash.View
{
	public partial class DeviceInformation
	{
		private global::Gtk.Notebook _informationPages;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label _deviceConnection;
		
		private global::Gtk.Button buttonClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget INTV.LtoFlash.View.DeviceInformation
			this.Name = "INTV.LtoFlash.View.DeviceInformation";
			this.Title = "LTO Flash! Device Information";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child INTV.LtoFlash.View.DeviceInformation.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this._informationPages = new global::Gtk.Notebook ();
			this._informationPages.CanFocus = true;
			this._informationPages.Name = "_informationPages";
			this._informationPages.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w2 = new global::Gtk.Label ();
			w2.Visible = true;
			this._informationPages.Add (w2);
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Information");
			this._informationPages.SetTabLabel (w2, this.label3);
			this.label3.ShowAll ();
			// Notebook tab
			global::Gtk.Label w3 = new global::Gtk.Label ();
			w3.Visible = true;
			this._informationPages.Add (w3);
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
			this._informationPages.SetTabLabel (w3, this.label4);
			this.label4.ShowAll ();
			// Notebook tab
			global::Gtk.Label w4 = new global::Gtk.Label ();
			w4.Visible = true;
			this._informationPages.Add (w4);
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Firmware");
			this._informationPages.SetTabLabel (w4, this.label5);
			this.label5.ShowAll ();
			// Notebook tab
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.Visible = true;
			this._informationPages.Add (w5);
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("File System");
			this._informationPages.SetTabLabel (w5, this.label6);
			this.label6.ShowAll ();
			w1.Add (this._informationPages);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this._informationPages]));
			w6.Position = 0;
			w6.Padding = ((uint)(1));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Connection:");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this._deviceConnection = new global::Gtk.Label ();
			this._deviceConnection.Name = "_deviceConnection";
			this._deviceConnection.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox2.Add (this._deviceConnection);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this._deviceConnection]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			w1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child INTV.LtoFlash.View.DeviceInformation.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString ("_Close");
			this.AddActionWidget (this.buttonClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonClose]));
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 568;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
