
// This file has been generated by the GUI designer. Do not modify.
namespace INTV.LtoFlash.View
{
	public partial class DeviceInformationPage
	{
		private global::Gtk.Table _infoTable;

		private global::Gtk.Entry _deviceName;

		private global::Gtk.Entry _deviceOwner;

		private global::Gtk.Entry _deviceUniqueId;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget INTV.LtoFlash.View.DeviceInformationPage
			global::Stetic.BinContainer.Attach(this);
			this.Name = "INTV.LtoFlash.View.DeviceInformationPage";
			// Container child INTV.LtoFlash.View.DeviceInformationPage.Gtk.Container+ContainerChild
			this._infoTable = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this._infoTable.Name = "_infoTable";
			this._infoTable.RowSpacing = ((uint)(6));
			this._infoTable.ColumnSpacing = ((uint)(6));
			this._infoTable.BorderWidth = ((uint)(6));
			// Container child _infoTable.Gtk.Table+TableChild
			this._deviceName = new global::Gtk.Entry();
			this._deviceName.CanFocus = true;
			this._deviceName.Name = "_deviceName";
			this._deviceName.IsEditable = true;
			this._deviceName.InvisibleChar = '•';
			this._infoTable.Add(this._deviceName);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this._infoTable[this._deviceName]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child _infoTable.Gtk.Table+TableChild
			this._deviceOwner = new global::Gtk.Entry();
			this._deviceOwner.CanFocus = true;
			this._deviceOwner.Name = "_deviceOwner";
			this._deviceOwner.IsEditable = true;
			this._deviceOwner.InvisibleChar = '•';
			this._infoTable.Add(this._deviceOwner);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this._infoTable[this._deviceOwner]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child _infoTable.Gtk.Table+TableChild
			this._deviceUniqueId = new global::Gtk.Entry();
			this._deviceUniqueId.CanFocus = true;
			this._deviceUniqueId.Name = "_deviceUniqueId";
			this._deviceUniqueId.IsEditable = false;
			this._deviceUniqueId.InvisibleChar = '•';
			this._infoTable.Add(this._deviceUniqueId);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this._infoTable[this._deviceUniqueId]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child _infoTable.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Name:");
			this._infoTable.Add(this.label1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this._infoTable[this.label1]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child _infoTable.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Owner:");
			this._infoTable.Add(this.label2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this._infoTable[this.label2]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child _infoTable.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Unique Id:");
			this._infoTable.Add(this.label3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this._infoTable[this.label3]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this._infoTable);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
